stages:
  - test

test-job:
  stage: test
  image: onmyshelf/test
  script:
    - cd /var/www/html/api/v1
    - mkdir -p inc/modules/import
    - mv /builds/onmyshelf/modules/import/* inc/modules/import/test
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - ./vendor/bin/pest
